version: '3.1'

services:

  oms-redis:
    container_name: oms-redis
    image: redis:alpine3.16
    restart: always
    volumes:
      - ./data:/data
      - ./redis.conf:/redis.conf
    command: redis-server /redis.conf
    ports:
      - 6379:6379
    networks:
      - oms-net

networks:
    oms-net:
      driver: bridge
